export const SUPPLIER_SAMPLE_BATCH_REFERENCE = "SAMPLE-HELPLIS-001";
export const SUPPLIER_SAMPLE_EXPORT_NAME = "SUPPLIER-SAMPLE-001";
export const SUPPLIER_SAMPLE_PUBLIC_CODES = ["SJRUPNZQ", "BCM3BLAJ", "H26EJYQW", "THAHHRYR", "TCR6MTJB"] as const;
